### ISSUE TITLE
telegram bot don't text masseges, chatgpt working only in code

### ISSUE THREAD

**Issue by vanechk** [Roshan-Here/ChatGPT#4]
Hello, Roshan-Here
I'm trying to use your bot, but it works only in code. Bot only sends me "Ask me any questions, i will fetch from CHATGPT AI" and then delete this message
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/74039440/216082277-3f7f7c10-1409-4587-a8b7-4e90d39183bf.png">

**Comment by Roshan-Here** [comment]
Sorry for the delay @vanechk  i think there must be some missing on your requirements!, if you are still on this i'm ready to help Contact me on [telegram](https://tx.me/Xequisting) , feel free to contact !
